version: "3.9"

services:
  api:
    container_name: lms-genie-dev-api
    build: . # Path to Dockerfile
    restart: unless-stopped
    ports:
      - 5500:5500 # Left is local and right is docker (I Believe)
      - 9229:9229 # Debugger port
    # Volumes is used so that we do not build the entire image upon a single file change
    volumes: # For persistence storage
      - .:/app # Left is local and after : is directory set in Dockerfile
      - /app/node_modules # Specifies to use Docker node_modules within Docker only and share everything else with us outside
    command: pnpm start:dev # This will override the CMD command which is present in Dockerfile
    env_file: .env
    depends_on:
      - mongodb
      - mailhog
      - redis
    environment:
      - NODE_ENV=development
      - PORT=5500
      - MONGO_URI=mongodb://root:rootpassword@mongodb:27017/lms-genie-dev?authSource=admin&retryWrites=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - lms-genie-dev

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  mongodb:
    container_name: lms-genie-dev-mongodb
    image: mongo
    restart: always
    # container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      # for persistence storage
      - mongodb-data:/data/db
    networks:
      - lms-genie-dev

  mongo-express:
    container_name: lms-genie-dev-mongo-express
    image: mongo-express
    depends_on:
      - mongodb
    # container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
      - ME_CONFIG_MONGODB_URL=mongodb://root:rootpassword@mongo:27017/
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin12345
    networks:
      - lms-genie-dev

  mailhog:
    container_name: lms-genie-dev-mailhog
    image: lytrax/mailhog:latest # https://github.com/mailhog/MailHog/issues/353#issuecomment-821137362
    restart: always
    logging:
      driver: "none" # disable saving logs
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP server
    environment:
      - SMTP_FROM_EMAIL=dev.lmsgenie@gmail.com
    networks:
      - lms-genie-dev

networks:
  lms-genie-dev:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
  redis-data:
    driver: local
