/* eslint-disable no-unused-vars */
export enum ROLES_LIST {
  ADMIN = "ADMIN",
  INSTRUCTOR = "INSTRUCTOR",
  ASSISTANT = "ASSISTANT",
  STUDENT = "STUDENT",
}

export enum COURSE_LEVELS {
  BEGINNER = "BEGINNER",
  INTERMEDIATE = "INTERMEDIATE",
  ADVANCE = "ADVANCE",
}

export enum DURATION_UNITS {
  MINUTES = "MINUTES",
  HOURS = "HOURS",
  DAYS = "DAYS",
  MONTHS = "MONTHS",
}

export enum CATEGORY_TYPES {
  MAIN_CATEGORY = "MAIN_CATEGORY",
  SUB_CATEGORY = "SUB_CATEGORY",
}
